// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiPgdAxkt4Nxkl0K5ZnWo9TSA_AQzQ-qg',
    appId: '1:9971678574:web:91dddb7df553f3b36b157f',
    messagingSenderId: '9971678574',
    projectId: 'temp-monitor-realtime',
    authDomain: 'temp-monitor-realtime.firebaseapp.com',
    databaseURL: 'https://temp-monitor-realtime-default-rtdb.firebaseio.com',
    storageBucket: 'temp-monitor-realtime.appspot.com',
    measurementId: 'G-D98ZYCEX2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOt5BfNEfhm9m1ZLATy6UV0W9F-IAGHgM',
    appId: '1:9971678574:android:099b6aa37e5cdac66b157f',
    messagingSenderId: '9971678574',
    projectId: 'temp-monitor-realtime',
    databaseURL: 'https://temp-monitor-realtime-default-rtdb.firebaseio.com',
    storageBucket: 'temp-monitor-realtime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3V8kgTSCDOBQ64tYIG7uH2w8RXNcfCPQ',
    appId: '1:9971678574:ios:bfd4eead3486f1756b157f',
    messagingSenderId: '9971678574',
    projectId: 'temp-monitor-realtime',
    databaseURL: 'https://temp-monitor-realtime-default-rtdb.firebaseio.com',
    storageBucket: 'temp-monitor-realtime.appspot.com',
    iosClientId: '9971678574-qu1i5b6t4mso776s4h9m9tqdu04cuin8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thermalHumidMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3V8kgTSCDOBQ64tYIG7uH2w8RXNcfCPQ',
    appId: '1:9971678574:ios:bfd4eead3486f1756b157f',
    messagingSenderId: '9971678574',
    projectId: 'temp-monitor-realtime',
    databaseURL: 'https://temp-monitor-realtime-default-rtdb.firebaseio.com',
    storageBucket: 'temp-monitor-realtime.appspot.com',
    iosClientId: '9971678574-qu1i5b6t4mso776s4h9m9tqdu04cuin8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thermalHumidMonitorApp',
  );
}
